version: '3.8'

services:
  wallpaper-api:
    build: .
    container_name: wallpaper-ai-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - wallpaper-network

networks:
  wallpaper-network:
    driver: bridge